# Aim:
* Extract features for logistic regression given some text
* Implement logistic regression from scratch
* Apply logistic regression on a natural language processing task
* Test logistic regression

We will be using a data set of tweets.

## Import functions and data

In [1]:
import nltk
from nltk.corpus import twitter_samples 
import pandas as pd

In [2]:

nltk.download('twitter_samples')
nltk.download('stopwords')

[nltk_data] Downloading package twitter_samples to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
import re
import string
import numpy as np

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import TweetTokenizer

In [4]:
#process_tweet(): cleans the text, tokenizes it into separate words, removes stopwords, and converts words to stems.
def process_tweet(tweet):
    """Process tweet function.
    Input:
        tweet: a string containing a tweet
    Output:
        tweets_clean: a list of words containing the processed tweet

    """
    tweet = str(tweet)
    stemmer = PorterStemmer()
    stopwords_english = stopwords.words('english')
    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)
    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)
    # remove hyperlinks
    tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)
    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)
    # tokenize tweets


    tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True,
                               reduce_len=True)
    tweet_tokens = tokenizer.tokenize(tweet)

    tweets_clean = []
    for word in tweet_tokens:
            
            #############################################################
            # 1 remove stopwords
            # 2 remove punctuation
            # 3 stemming word
            # 4 Add it to tweets_clean
            if(word in stopwords_english):
                continue
            
            punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
            for c in word:
                if c in punc:
                    word = word.replace(c, "")
            
            word = stemmer.stem(word)
            
            if len(word) == 0:
                continue
                
            tweets_clean.append(word)
    return tweets_clean

In [5]:
#build_freqs counts how often a word in the 'corpus' (the entire set of tweets) was associated with
  # a positive label '1'         or 
  # a negative label '0', 

#then builds the freqs dictionary, where each key is a (word,label) tuple, 

#and the value is the count of its frequency within the corpus of tweets.

def build_freqs(tweets, ys):
    """Build frequencies.
    Input:
        tweets: a list of tweets
        ys: an m x 1 array with the sentiment label of each tweet
            (either 0 or 1)
    Output:
        freqs: a dictionary mapping each (word, sentiment) pair to its
        frequency
    """
    # Convert np array to list since zip needs an iterable.
    # The squeeze is necessary or the list ends up with one element.
    # Also note that this is just a NOP if ys is already a list.
    yslist = np.squeeze(ys).tolist()

    # Start with an empty dictionary and populate it by looping over all tweets
    # and over all processed words in each tweet.
    freqs = {}

    for y, tweet in zip(yslist, tweets):
        for word in process_tweet(tweet):
            pair = (word, y)
            if pair not in freqs:
                freqs[pair] = 1
            else:
                freqs[pair] += 1
            
            #############################################################
            #Update the count of pair if present, set it to 1 otherwise
            

    return freqs

### Prepare the data
* The `twitter_samples` contains subsets of 5,000 positive tweets, 5,000 negative tweets, and the full set of 10,000 tweets.  

In [6]:
# select the set of positive and negative tweets
all_positive_tweets = twitter_samples.strings('positive_tweets.json')
all_negative_tweets = twitter_samples.strings('negative_tweets.json')

* Train test split: 20% will be in the test set, and 80% in the training set.


In [7]:
# split the data into two pieces, one for training and one for testing
#############################################################
from sklearn.model_selection import train_test_split
import copy

train_pos, test_pos = train_test_split(all_positive_tweets, test_size = 0.20, random_state = 136) 
train_neg, test_neg = train_test_split(all_negative_tweets, test_size = 0.20, random_state = 136) 

X_train = copy.deepcopy(train_pos)
X_train.extend(train_neg)

X_test=copy.deepcopy(test_pos)
X_test.extend(test_neg)

train_pos=np.array(train_pos)
train_neg=np.array(train_neg)
test_pos=np.array(test_pos)
test_neg=np.array(test_neg)

X_train = np.array(X_train)
X_test = np.array(X_test)




* Create the numpy array of positive labels and negative labels.

In [8]:
print(X_train.shape,train_pos.shape,train_neg.shape)

(8000,) (4000,) (4000,)


In [9]:
# combine positive and negative labels
train_y = np.append(np.ones((len(train_pos), 1)), np.zeros((len(train_neg), 1)), axis=0)
test_y = np.append(np.ones((len(test_pos), 1)), np.zeros((len(test_neg), 1)), axis=0)
train_y

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

* Create the frequency dictionary using the  `build_freqs()` function.  
    


In [10]:
# create frequency dictionary
#############################################################
freqs = build_freqs(X_train, train_y)

# check the output
print("type(freqs) = " + str(type(freqs)))
print("len(freqs) = " + str(len(freqs.keys())))

type(freqs) = <class 'dict'>
len(freqs) = 11234


* HERE, The `freqs` dictionary is the frequency dictionary that's being built. 
* The key is the tuple (word, label), such as ("happy",1) or ("happy",0).  The value stored for each key is the count of how many times the word "happy" was associated with a positive label, or how many times "happy" was associated with a negative label.

### Process tweet

In [11]:
# Example
print('This is an example of a positive tweet: \n', X_train[0])
print('\nThis is an example of the processed version of the tweet: \n', process_tweet(X_train[0]))

This is an example of a positive tweet: 
 @EnRoute2BeFit If people don't have anything postive to say they should keep their opinions to themselves :) Looking good / strong as always

This is an example of the processed version of the tweet: 
 ['peopl', 'anyth', 'postiv', 'say', 'keep', 'opinion', 'look', 'good', 'strong', 'alway']


#Logistic regression :


### Sigmoid

$$ h(z) = \frac{1}{1+\exp^{-z}} $$

It maps the input 'x' to a value that ranges between 0 and 1, and so it can be treated as a probability. 




In [12]:
def sigmoid(z): 
       
    # calculate the sigmoid of z
    #############################################################
    h = 1/(1+np.exp(-z))
    
    return h

### Logistic regression: regression and a sigmoid

Logistic regression takes a regular linear regression, and applies a sigmoid to the output of the linear regression.

Logistic regression
$$ h(z) = \frac{1}{1+\exp^{-z}}$$
$$z = \theta_0 x_0 + \theta_1 x_1 + \theta_2 x_2 + ... \theta_N x_N$$


#### Update the weights:Gradient Descent


$$\nabla_{\theta_j}J(\theta) = \frac{1}{m} \sum_{i=1}^m(h^{(i)}-y^{(i)})x_j $$

* To update the weight $\theta_j$, we adjust it by subtracting a fraction of the gradient determined by $\alpha$:
$$\theta_j = \theta_j - \alpha \times \nabla_{\theta_j}J(\theta) $$

* The learning rate $\alpha$ is a value that we choose to control how big a single update will be.


In [13]:
def gradientDescent(x, y, theta, alpha, num_iters):
  
    # get 'm', the number of rows in matrix x
    m = len(x)
    
    for i in range(0, num_iters):
        # get z, the dot product of x and theta
        #############################################################
        z =  np.dot(x,theta)
        # get the sigmoid of z
        #############################################################
        h = sigmoid(z)
        # calculate the cost function
        J = (-1/m)*(y.T @ np.log(h) + (1-y).T @ np.log(1-h))

        # update the weights theta
        #############################################################
        for j in range(len(x[0])):
            theta[j][0] = theta[j][0] - alpha * np.sum((h-y)*x[:,j])
        
    J = float(J)
    return J, theta

## Extracting the features

* Given a list of tweets, extract the features and store them in a matrix. You will extract two features.
    * The first feature is the number of positive words in a tweet.
    * The second feature is the number of negative words in a tweet. 
* Then train your logistic regression classifier on these features.
* Test the classifier on a validation set. 


In [14]:
def extract_features(tweet, freqs):
    '''
    Input: 
        tweet: a list of words for one tweet
        freqs: a dictionary corresponding to the frequencies of each tuple (word, label)
    Output: 
        x: a feature vector of dimension (1,3)
    '''
    # tokenizes, stems, and removes stopwords
    #############################################################
    word_l = process_tweet(tweet)
    
    # 3 elements in the form of a 1 x 3 vector
    x = np.zeros((1, 3)) 
    
    #bias term is set to 1
    x[0,0] = 1 
        
    # loop through each word in the list of words
    for word in word_l:
        if (word,1) in freqs:
            x[0][1]+=1
        if (word,0) in freqs:
            x[0][2]+=1
            
        # increment the word count for the positive label 1
        #############################################################
        
        # increment the word count for the negative label 0
        #############################################################
    
    assert(x.shape == (1, 3))
    return x

In [15]:
# Check the function

# test 1
# test on training data
tmp1 = extract_features(X_train[0], freqs)
print(tmp1)

[[ 1. 10.  8.]]


In [16]:
# test 2:
# check for when the words are not in the freqs dictionary
tmp2 = extract_features('Hariom pandya', freqs)
print(tmp2)

[[1. 0. 0.]]


## Training Your Model

To train the model:
* Stack the features for all training examples into a matrix `X`. 
* Call `gradientDescent`

In [17]:
# collect the features 'x' and stack them into a matrix 'X'
X = np.zeros((len(X_train), 3))
for i in range(len(X_train)):
    X[i, :]= extract_features(X_train[i], freqs)

# training labels corresponding to X
Y = train_y
print(len(X[0]))
# Apply gradient descent
J, theta = gradientDescent(X, Y, np.zeros((3, 1)), 1e-9, 1500)
print(f"The cost after training is {J:.8f}.")


3
The cost after training is 0.69314718.


# Test logistic regression

Predict whether a tweet is positive or negative.

* Given a tweet, process it, then extract the features.
* Apply the model's learned weights on the features to get the logits.
* Apply the sigmoid to the logits to get the prediction (a value between 0 and 1).

$$y_{pred} = sigmoid(\mathbf{x} \cdot \theta)$$

In [18]:
def predict_tweet(tweet, freqs, theta):
    '''
    Input: 
        tweet: a string
        freqs: a dictionary corresponding to the frequencies of each tuple (word, label)
        theta: (3,1) vector of weights
    Output: 
        y_pred: the probability of a tweet being positive or negative
    '''
    
    # extract the features of the tweet and store it into x
    #############################################################
    x = extract_features(tweet,freqs)
    
    # make the prediction using x and theta
    #############################################################
    y_pred = sigmoid(np.dot(x,theta))
    
    
    return y_pred

In [19]:
# Run this cell to test your function
for tweet in ['I am happy', 'I am bad', 'this movie should have been great.', 'great', 'great great', 'great great great', 'great great great great']:
    print( '%s -> %f' % (tweet, predict_tweet(tweet, freqs, theta)))

I am happy -> 0.500000
I am bad -> 0.500000
this movie should have been great. -> 0.500000
great -> 0.500000
great great -> 0.500000
great great great -> 0.500000
great great great great -> 0.500000


## Check performance using the test set


In [20]:
def test_logistic_regression(test_x, test_y, freqs, theta):
    """
    Input: 
        test_x: a list of tweets
        test_y: (m, 1) vector with the corresponding labels for the list of tweets
        freqs: a dictionary with the frequency of each pair (or tuple)
        theta: weight vector of dimension (3, 1)
    Output: 
        accuracy: (# of tweets classified correctly) / (total # of tweets)
    """
    
    
    # the list for storing predictions
    y_hat = []
    
    for tweet in test_x:
        # get the label prediction for the tweet
        y_pred = predict_tweet(tweet, freqs, theta)
        
        if y_pred > 0.5:
            # append 1.0 to the list
            y_hat.append(1)
        else:
            # append 0 to the list
            y_hat.append(0)

    # With the above implementation, y_hat is a list, but test_y is (m,1) array
    # convert both to one-dimensional arrays in order to compare them using the '==' operator
    count=0
    y_hat=np.array(y_hat)
    m=len(test_y)
    #print(m)
    
    test_y=np.reshape(test_y,m)
    #print(y_hat.shape)
    #print(test_y.shape)
    
    accuracy = ((test_y == y_hat).sum())/m
    
    return accuracy

In [21]:
tmp_accuracy = test_logistic_regression(X_test, test_y, freqs, theta)
print(f"Logistic regression model's accuracy = {tmp_accuracy:.4f}")

Logistic regression model's accuracy = 0.5000


# Lab Assignment:

## Replace Manual version of Logistic Regression with TF based version. 
#### [Reference : Lab-6]

In [11]:
import nltk
from nltk.corpus import twitter_samples 
import pandas as pd
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [12]:
nltk.download('twitter_samples')
nltk.download('stopwords')

[nltk_data] Downloading package twitter_samples to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
import re
import string
import numpy as np
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import TweetTokenizer

In [14]:
all_positive_tweets = twitter_samples.strings('positive_tweets.json')
all_negative_tweets = twitter_samples.strings('negative_tweets.json')

In [15]:
from sklearn.model_selection import train_test_split
import copy

train_pos, test_pos = train_test_split(all_positive_tweets, test_size = 0.20, random_state = 136) 
train_neg, test_neg = train_test_split(all_negative_tweets, test_size = 0.20, random_state = 136) 

X_train = copy.deepcopy(train_pos)
X_train.extend(train_neg)

X_test=copy.deepcopy(test_pos)
X_test.extend(test_neg)

train_pos=np.array(train_pos)
train_neg=np.array(train_neg)
test_pos=np.array(test_pos)
test_neg=np.array(test_neg)

train_x = np.array(X_train)
test_x = np.array(X_test)


In [16]:
def process_tweet(tweet):
    stemmer = PorterStemmer()
    stopwords_english = stopwords.words('english')

    tweet = re.sub(r'\$\w*', '', tweet)
    tweet = re.sub(r'^RT[\s]+', '', tweet)
    tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)
    tweet = re.sub(r'#', '', tweet)
   
    tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True,
                               reduce_len=True)
    tweet_tokens = tokenizer.tokenize(tweet)

    tweets_clean = []
    for word in tweet_tokens:
            if(word not in stopwords_english and word not in string.punctuation):
                steam_word = stemmer.stem(word)
                tweets_clean.append(steam_word)
    return tweets_clean

In [17]:
def build_freqs(tweets, ys):
    yslist = np.squeeze(ys).tolist()
    freqs = {}
    for y, tweet in zip(yslist, tweets):
        for word in process_tweet(tweet):
            pair = (word, y)
            if pair in freqs:
                freqs[pair] += 1
            else:
                freqs[pair] = 1
    return freqs

In [18]:
train_y = np.append(np.ones((len(train_pos), 1)), np.zeros((len(train_neg), 1)), axis=0)
test_y = np.append(np.ones((len(test_pos), 1)), np.zeros((len(test_neg), 1)), axis=0)
train_y

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [19]:
freqs = build_freqs(train_x,train_y)

print("\ntype(freqs) = " + str(type(freqs)))
print("len(freqs) = " + str(len(freqs.keys())))


type(freqs) = <class 'dict'>
len(freqs) = 11419


In [20]:
print('Example of positive tweet: \n', train_x[0])
print('\nExample of the processed version of the tweet: \n', process_tweet(train_x[0]))

Example of positive tweet: 
 @EnRoute2BeFit If people don't have anything postive to say they should keep their opinions to themselves :) Looking good / strong as always

Example of the processed version of the tweet: 
 ['peopl', 'anyth', 'postiv', 'say', 'keep', 'opinion', ':)', 'look', 'good', 'strong', 'alway']


In [21]:
def extract_features(tweet, freqs):
 
    word_l = process_tweet(tweet)
    x = np.zeros((1, 2)) 
    
    for word in word_l:
        if((word,1) in freqs):
            x[0,0]+=freqs[word,1]
    
        if((word,0) in freqs):
            x[0,1]+=freqs[word,0]
    
    assert(x.shape == (1, 2))
    return x[0]

In [22]:
tmp1 = extract_features(train_x[0], freqs)
print(tmp1)

[3387.  352.]


In [23]:
def predict_tweet(tweet):
    with tf.Session() as sess:
        saver.restore(sess,save_path='TSession')
        data_i=[]
        for t in tweet:
            data_i.append(extract_features(t,freqs))
        data_i=np.asarray(data_i)
        return sess.run(tf.nn.sigmoid(tf.add(tf.matmul(a=data_i,b=W,transpose_b=True),b)))
        print("Fail")
    return 

In [24]:
b=tf.Variable(np.random.randn(1),name="Bias")
W=tf.Variable(np.random.randn(1,2),name="Bias")

In [25]:
data=[]
for t in train_x:
    data.append(extract_features(t,freqs))
data=np.asarray(data)

In [26]:
Y_hat = tf.nn.sigmoid(tf.add(tf.matmul(np.asarray(data), W,transpose_b=True), b)) 
print(Y_hat)
ta=np.asarray(train_y)
cost = tf.nn.sigmoid_cross_entropy_with_logits( 
                    logits = Y_hat, labels = ta) 
print("\n",cost)

Tensor("Sigmoid:0", shape=(8000, 1), dtype=float64)

 Tensor("logistic_loss:0", shape=(8000, 1), dtype=float64)


In [27]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-4,name="GradientDescent").minimize(cost) 
init = tf.global_variables_initializer() 

In [28]:
saver = tf.train.Saver()
with tf.Session() as sess:
  
    sess.run(init)
    print("Bias",sess.run(b))
    print("Weight",sess.run(W))
    for epoch in range(400):
        sess.run(optimizer)
        preds=sess.run(Y_hat)
        acc=((preds==ta).sum())/len(train_y)
        accu=[]
        repoch=False
        if repoch:
            accu.append(acc)
        if epoch % 1000 == 0:
            print("Accuracy",acc)
        saved_path = saver.save(sess, 'TSession')

Bias [0.28828369]
Weight [[ 0.78697415 -0.13872724]]
Accuracy 0.92975


In [29]:
preds=predict_tweet(test_x)
print(preds,len(test_y))

INFO:tensorflow:Restoring parameters from TSession
[[1.]
 [1.]
 [1.]
 ...
 [0.]
 [0.]
 [0.]] 2000


In [34]:
def calculate_accuracy(x,y):
    if len(x)!=len(y):
        return
    return ((x==y).sum())/len(y)

In [35]:
calculate_accuracy(preds,test_y)

0.9215