### Task 1: Try the algo on Dataset3 - LabelEncoding of features:and Train test Division 95%-5%

In [26]:
import pandas as pd
import numpy as np


In [61]:
data=  pd.read_csv('./PracticeDataSets/Dataset3.csv')
data

Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0

In [62]:
from sklearn.preprocessing import LabelEncoder

In [63]:
le=LabelEncoder()
for i in range(0,3):
    data.iloc[:,[i]]=le.fit_transform(data.iloc[:,[i]])

C:\Users\harsh\anaconda3\envs\ML\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [74]:
data

Outlook  Temp  Wind  Humidity  Class
0         1     1     0         1      0
1         1     1     1         2      0
2         0     1     0         1      1
3         1     2     0         1      1
4         2     0     0         1      1
5         0     0     1         0      0
6         0     0     1         1      1
7         1     2     0         1      0
8         0     0     0         0      1
9         2     2     0         2      1
10        1     0     1         2      0
11        0     2     1         0      1
12        0     1     0         1      1
13        2     2     1         1      0

In [80]:
X=data.iloc[:,:-1].values
Y=data.iloc[:,-1].values
print(X.shape)
print(Y.shape)

(14, 4)
(14,)


In [81]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,
                        Y, test_size = 0.05, random_state = 136)

In [82]:
X_train.shape

(13, 4)

In [83]:
from sklearn.naive_bayes import GaussianNB

In [84]:
nb=GaussianNB()
nb.fit(X_train,Y_train)

GaussianNB()

In [86]:
nb.predict([[1,2,0,1],[2,0,1,2]]) #Rainy,Mild,False,Normal  Sunny,Cool,True,High

array([1, 0], dtype=int64)

In [87]:
predicted_data=nb.predict(X_test)
predicted_data

array([1], dtype=int64)

In [88]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(Y_test, predicted_data))

Accuracy: 1.0


In [89]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, predicted_data,labels=[0,1])

array([[0, 0],
       [0, 1]], dtype=int64)

In [90]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(Y_test, predicted_data, average=None)
recall = recall_score(Y_test, predicted_data, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.]
recall: [1.]


### Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 50%-50%

In [100]:
data=pd.read_csv('./PracticeDataSets/Wisconsin.csv')
data=data.iloc[:,1:32]
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [101]:
X=data.iloc[:,1:].values
Y=data.iloc[:,0].values

In [103]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,
                        Y, test_size = 0.5, random_state = 136)
print(X_train.shape, X_test.shape)

(284, 30) (285, 30)


In [104]:
from sklearn.naive_bayes import GaussianNB

nb=GaussianNB()
nb.fit(X_train,Y_train)

GaussianNB()

In [105]:
predicted_data=nb.predict(X_test)
predicted_data

array(['M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'M', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'M', 'M',
       'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'M',
       'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'B',
       'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B

In [106]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, predicted_data)

array([[179,   8],
       [  7,  91]], dtype=int64)

In [108]:
confusion_matrix(Y_test, predicted_data).ravel()

array([179,   8,   7,  91], dtype=int64)

In [115]:
from sklearn import metrics

precision = precision_score(Y_test, predicted_data, average=None)
recall = recall_score(Y_test, predicted_data, average=None)

print("Accuracy: {}".format(metrics.accuracy_score(Y_test, predicted_data)))
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.9473684210526315
precision: [0.96236559 0.91919192]
recall: [0.95721925 0.92857143]
