In [67]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [68]:
# Imports
import torch.nn as nn

In [69]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [70]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [71]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [72]:
# Define dataset
dataset = torch.utils.data.TensorDataset(inputs,targets)

In [73]:
# Define data loader
dataloader = torch.utils.data.DataLoader(dataset,batch_size=5)

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [74]:
# Define model
model = nn.Linear(inputs.shape[1],targets.shape[1])
model.parameters()

<generator object Module.parameters at 0x00000209C64EF820>

### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [75]:
# Define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=1e-4)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [76]:
# Import nn.functional
import torch.nn.functional as F

In [77]:
# Define loss function
loss_fn = F.mse_loss

### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [78]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in dataloader:
#             Generate predictions
            pred = model(xb)
            loss = loss_fn(yb,pred)
            loss.backward()
            opt.step()
            opt.zero_grad()
        print('Training loss: ', loss_fn(model(inputs), targets))

In [79]:
# Train the model for 100 epochs
fit(120 , model , loss_fn, optimizer)

Training loss:  tensor(3287.7698, grad_fn=<MseLossBackward>)
Training loss:  tensor(966.5102, grad_fn=<MseLossBackward>)
Training loss:  tensor(345.9995, grad_fn=<MseLossBackward>)
Training loss:  tensor(158.8325, grad_fn=<MseLossBackward>)
Training loss:  tensor(89.2005, grad_fn=<MseLossBackward>)
Training loss:  tensor(56.0684, grad_fn=<MseLossBackward>)
Training loss:  tensor(37.0885, grad_fn=<MseLossBackward>)
Training loss:  tensor(25.0959, grad_fn=<MseLossBackward>)
Training loss:  tensor(17.1931, grad_fn=<MseLossBackward>)
Training loss:  tensor(11.8986, grad_fn=<MseLossBackward>)
Training loss:  tensor(8.3281, grad_fn=<MseLossBackward>)
Training loss:  tensor(5.9131, grad_fn=<MseLossBackward>)
Training loss:  tensor(4.2764, grad_fn=<MseLossBackward>)
Training loss:  tensor(3.1651, grad_fn=<MseLossBackward>)
Training loss:  tensor(2.4089, grad_fn=<MseLossBackward>)
Training loss:  tensor(1.8927, grad_fn=<MseLossBackward>)
Training loss:  tensor(1.5389, grad_fn=<MseLossBackward>)

In [80]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.2551,  70.3341],
        [ 82.1251, 100.6674],
        [118.7363, 132.9251],
        [ 21.0867,  37.0038],
        [101.8771, 119.1711],
        [ 57.2551,  70.3341],
        [ 82.1251, 100.6674],
        [118.7363, 132.9251],
        [ 21.0867,  37.0038],
        [101.8771, 119.1711],
        [ 57.2551,  70.3341],
        [ 82.1251, 100.6674],
        [118.7363, 132.9251],
        [ 21.0867,  37.0038],
        [101.8771, 119.1711]], grad_fn=<AddmmBackward>)

In [81]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

### Task 1

In [82]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [83]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(inputs,targets,test_size=0.3,random_state=136)

In [84]:
model.fit(X_train,Y_train)

LinearRegression()

In [85]:
predictions = model.predict(X_test)

In [86]:
print(predictions)

[[ 20.568804  37.100315]
 [ 20.568804  37.100315]
 [ 57.442204  69.89892 ]
 [ 82.11636  100.92175 ]
 [ 57.442204  69.89892 ]]


In [87]:
print(Y_test)

tensor([[ 22.,  37.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 81., 101.],
        [ 56.,  70.]])


In [88]:
from sklearn.metrics import mean_squared_error

print(mean_squared_error(Y_test,predictions))

0.9549499


### Task 2

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [8]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print()
print(r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.54638447, 0.64195077],
       [0.84526841, 0.87724339],
       [0.08659259, 0.63145962]])>

<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-0.57545064, -1.34702049])>


In [9]:
def model(s):
    return s @ v + r

In [10]:
prediction = model(inputs)
prediction

<tf.Tensor: shape=(15, 2), dtype=float64, numpy=
array([[ 99.66708053, 131.44345715],
       [129.07108201, 174.68133445],
       [165.24833544, 208.67796976],
       [ 94.70623275, 125.21743033],
       [124.33232652, 171.36512237],
       [ 99.66708053, 131.44345715],
       [129.07108201, 174.68133445],
       [165.24833544, 208.67796976],
       [ 94.70623275, 125.21743033],
       [124.33232652, 171.36512237],
       [ 99.66708053, 131.44345715],
       [129.07108201, 174.68133445],
       [165.24833544, 208.67796976],
       [ 94.70623275, 125.21743033],
       [124.33232652, 171.36512237]])>

In [11]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(3755.362945061839, shape=(), dtype=float64)


In [13]:
epochs = 25
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f"Epoch: {epoch_count} \n Loss: {current_loss.numpy()} \n\n")

Epoch: 0 
 Loss: 20.106306785888883 


Epoch: 1 
 Loss: 19.5618259073313 


Epoch: 2 
 Loss: 19.049542248351578 


Epoch: 3 
 Loss: 18.566148318810846 


Epoch: 4 
 Loss: 18.108730714662446 


Epoch: 5 
 Loss: 17.67472188014168 


Epoch: 6 
 Loss: 17.261857827573557 


Epoch: 7 
 Loss: 16.86814106736379 


Epoch: 8 
 Loss: 16.491808098681084 


Epoch: 9 
 Loss: 16.131300894924063 


Epoch: 10 
 Loss: 15.785241889932232 


Epoch: 11 
 Loss: 15.452412033032045 


Epoch: 12 
 Loss: 15.13173153494807 


Epoch: 13 
 Loss: 14.822242973571406 


Epoch: 14 
 Loss: 14.523096469552165 


Epoch: 15 
 Loss: 14.233536677497908 


Epoch: 16 
 Loss: 13.952891369884112 


Epoch: 17 
 Loss: 13.68056141821786 


Epoch: 18 
 Loss: 13.416012000027585 


Epoch: 19 
 Loss: 13.158764881313486 


Epoch: 20 
 Loss: 12.908391642560854 


Epoch: 21 
 Loss: 12.664507732608877 


Epoch: 22 
 Loss: 12.426767248869863 


Epoch: 23 
 Loss: 12.194858354848744 


Epoch: 24 
 Loss: 11.96849925683856 




In [14]:
model(inputs)

<tf.Tensor: shape=(15, 2), dtype=float64, numpy=
array([[ 57.48549059,  70.37593437],
       [ 79.53981645,  99.03684611],
       [124.24196763, 136.56129279],
       [ 23.21788831,  38.55120985],
       [ 95.91925763, 115.13311738],
       [ 57.48549059,  70.37593437],
       [ 79.53981645,  99.03684611],
       [124.24196763, 136.56129279],
       [ 23.21788831,  38.55120985],
       [ 95.91925763, 115.13311738],
       [ 57.48549059,  70.37593437],
       [ 79.53981645,  99.03684611],
       [124.24196763, 136.56129279],
       [ 23.21788831,  38.55120985],
       [ 95.91925763, 115.13311738]])>