# NumPy

In [1]:
import numpy as np

In [2]:
alist=[1,2,3,4,5,6,7,8,]
print(type(alist))
narray=np.array(alist)
print(type(narray))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
print(alist)
print(narray)

[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]


In [4]:
print(narray+narray) #Adds individual elements
print(alist+alist)   #Concats the list 
print(narray*3)      #Multiplies to individual elements
print(alist*3)       #Concates list 3 times

[ 2  4  6  8 10 12 14 16]
[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]
[ 3  6  9 12 15 18 21 24]
[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
mat1=np.array([narray,narray,narray])
mat2=np.array([alist,alist,alist])
print(mat1)
print(mat2)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [6]:
okmat=np.array([[1,2],[3,4]]) #All rows should have same elements otherwise algebric operation might
print(okmat*3)                #malform

[[ 3  6]
 [ 9 12]]


In [7]:
badmat=np.array([[1,2],[2,3,4]])
print(badmat*4)

[list([1, 2, 1, 2, 1, 2, 1, 2]) list([2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4])]


<ipython-input-7-2d713981dff4>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  badmat=np.array([[1,2],[2,3,4]])


In [8]:
res=okmat*2+1
print(res)

[[3 5]
 [7 9]]


In [9]:
res=okmat+okmat
print(res)
res=okmat-okmat
print(okmat)

[[2 4]
 [6 8]]
[[1 2]
 [3 4]]


In [10]:
res=okmat*okmat
print(res)

[[ 1  4]
 [ 9 16]]


In [11]:
print(okmat.T) #Transpose of matrix

[[1 3]
 [2 4]]


In [12]:
narray=np.array([1,2,3,4])
print(narray.T)  #Transpose doesnot affect 1D array

[1 2 3 4]


# Normalizing


In [13]:
narray=np.array([1,2,3,4])
normalized=np.linalg.norm(narray)
print(normalized)

nmat=np.array([[1,2],[3,4]])
normalized=np.linalg.norm(nmat) #Treats matrix same as 1D array
print(normalized)

5.477225575051661
5.477225575051661


In [14]:
nparray1 = np.array([0, 1, 2, 3]) 
nparray2 = np.array([4, 5, 6, 7]) 
flavor1 = np.dot(nparray1, nparray2) # Way-1
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2) # Way-2
print(flavor2)

flavor3 = nparray1 @ nparray2 # Way-3
print(flavor3)

flavor4 = 0 # Way-4
for a, b in zip(nparray1, nparray2):
    flavor4 += a * b
print(flavor4)

38
38
38
38


In [15]:
narray=np.array([[1,2],[3,4],[5,6]])
sumByCols=np.sum(narray,axis=0)
sumByRows=np.sum(narray,axis=1)
sm=np.sum(narray)
print(sumByCols)
print(sumByRows)
print(sm)

[ 9 12]
[ 3  7 11]
21


In [16]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) 

mean = np.mean(nparray2) # Get the mean for the whole matrix
meanByCols = np.mean(nparray2, axis=0) # Get the mean for each column. Returns 2 elements
meanByRows = np.mean(nparray2, axis=1)

print(mean,meanByRows,meanByCols,)

0.0 [0. 0. 0.] [ 2. -2.]


In [17]:
narray= np.array([[1,2],[3,4],[5,6]])
centered=narray - np.mean(narray, axis=0)
print(narray)
print(centered)

[[1 2]
 [3 4]
 [5 6]]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


# Excercise

In [22]:
arr1,arr2= np.random.rand(2,3),np.random.rand(3,2)

print(arr1)
print(arr2)

[[0.26744542 0.10445335 0.57130856]
 [0.40501394 0.16258668 0.14000017]]
[[0.45173753 0.64797111]
 [0.79766027 0.55610976]
 [0.00255738 0.61211701]]


In [23]:
print(np.dot(arr1,arr2))

[[0.20559447 0.58109212]
 [0.31300696 0.43854986]]


In [27]:
print(np.matmul(arr1,arr2))

[[0.20559447 0.58109212]
 [0.31300696 0.43854986]]


In [28]:
print(np.mean(arr1))

0.2751346864700374


In [29]:
import pandas as pd

In [30]:
df=pd.read_csv('D:/Term/ML/136-Harshit-Tarsariya/01/mtcars.csv')
df

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [31]:
df=np.array(df.drop(['model'],axis=1))

In [32]:
narray=df - np.mean(df, axis=0)

In [33]:
narray

array([[ 9.09375000e-01, -1.87500000e-01, -7.07218750e+01,
        -3.66875000e+01,  3.03437500e-01, -5.97250000e-01,
        -1.38875000e+00, -4.37500000e-01,  5.93750000e-01,
         3.12500000e-01,  1.18750000e+00],
       [ 9.09375000e-01, -1.87500000e-01, -7.07218750e+01,
        -3.66875000e+01,  3.03437500e-01, -3.42250000e-01,
        -8.28750000e-01, -4.37500000e-01,  5.93750000e-01,
         3.12500000e-01,  1.18750000e+00],
       [ 2.70937500e+00, -2.18750000e+00, -1.22721875e+02,
        -5.36875000e+01,  2.53437500e-01, -8.97250000e-01,
         7.61250000e-01,  5.62500000e-01,  5.93750000e-01,
         3.12500000e-01, -1.81250000e+00],
       [ 1.30937500e+00, -1.87500000e-01,  2.72781250e+01,
        -3.66875000e+01, -5.16562500e-01, -2.25000000e-03,
         1.59125000e+00,  5.62500000e-01, -4.06250000e-01,
        -6.87500000e-01, -1.81250000e+00],
       [-1.39062500e+00,  1.81250000e+00,  1.29278125e+02,
         2.83125000e+01, -4.46562500e-01,  2.22750000e-01,
  